# Generated by Django 5.1.4 on 2024-12-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='construction_year',
        ),
        migrations.RemoveField(
            model_name='building',
            name='name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='hired_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
