# Generated by Django 5.1.4 on 2024-12-19 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARC', '0002_remove_building_construction_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='building',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='ARC.building'),
        ),
    ]
